#!/bin/python3

import math
import os
import random
import re
import sys

def hourglassSum(arr):
    j = 1
    i = 0
    arrsum = list()
    while j <= 4 :
        while i <= 3:
            s = arr[i][j-1] + arr[i][j] + arr[i][j+1] + arr[i+1][j] + arr[i+2][j] + arr[i+2][j-1] + arr[i+2][j+1]
            arrsum.append(s)
            i += 1
        i = 0
        j += 1
    return(max(arrsum))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr = []

    for _ in range(6):
        arr.append(list(map(int, input().rstrip().split())))

    result = hourglassSum(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
