#!/bin/python3

import math
import os
import random
import re
import sys

def countingValleys(n, s):
    k = list()
    j = 0
    c = 0
    for i in range(n):
        if s[i] == 'U':
            j += 1
            #k.append(j)
        elif s[i] == 'D':
            j += -1
        else:
            break
        k.append(j)
    
    for h in range(n):
        if h == 0 and k[h] < 0:
            c += 1
        elif k[h] < 0 and k[h-1] == 0:
            c += 1
        else:
            pass
    return c
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    s = input()

    result = countingValleys(n, s)

    fptr.write(str(result) + '\n')

    fptr.close()
