#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter
# Complete the makeAnagram function below.
def makeAnagram(a, b):
    a_count = Counter(a)
    b_count = Counter(b)
    word = 0
    for i in a_count.keys():
        if i in b_count.keys():
            word += min(a_count[i], b_count[i])
    return(sum(a_count.values())+sum(b_count.values())-2*word)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = input()

    b = input()

    res = makeAnagram(a, b)

    fptr.write(str(res) + '\n')

    fptr.close()
