#!/bin/python3

import math
import os
import random
import re
import sys

def maximumToys(prices, k):
    prices.sort()
    sum = 0
    i = 0
    for n in range(len(prices)):
        if sum < k:
            sum += prices[n]
            i += 1
    return i-1

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = input().split()

    n = int(nk[0])

    k = int(nk[1])

    prices = list(map(int, input().rstrip().split()))

    result = maximumToys(prices, k)

    fptr.write(str(result) + '\n')

    fptr.close()
