#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the sockMerchant function below.
def sockMerchant(n, ar):
    dic = dict()
    k = 0
    for i in range(n):
        if ar[i] in dic:
            dic[ar[i]] += 1
        else:
            dic[ar[i]] = 1
    for j in dic:
        k += dic[j]//2
    return k

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
